# Generated by Django 4.0.2 on 2022-02-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=640)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=640)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('comments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.comment')),
                ('friends', models.ManyToManyField(to='socialmedia_api.User')),
                ('posts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postedto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia_api.post'),
        ),
    ]
